services:
  db:
    image: postgres:15
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  backend:
    build: ./backend
    # 開発時は Dockerfile の CMD を上書きして、常に最新のコードで実行
    command: bin/rails server -b 0.0.0.0
    volumes:
      - ./backend:/rails
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/backend_development
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      # コンテナ内の node_modules をホスト側で上書きしないための設定
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend